M48
; DRILL file {KiCad (6.0.11)} date Sun Oct  1 19:45:09 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-01T19:45:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
%
G90
G05
T1
X3.4732Y-1.9219
X3.6268Y-1.9219
T2
X2.9016Y-2.6378
X2.9016Y-2.9331
T0
M30
